### ISSUE TITLE
decorate apispec functions

### ISSUE THREAD

**Issue by algrebe** [deep-compute/django-yada#2]
When API functions are called directly through URL dispatcher, we need to extract the parameters from the request body before calling the function.

**Comment by kumar550** [comment]
**Status:**
@algrebe 
- We understood the existing code and started enhancing to extract parameters from the request body

**Comment by kumar550** [comment]
**Status:**
- We had written one decorator in views.py and trying to extract the input parameters 

**Target:**
- We will enhance code and fix the error
